import { StyleSheet } from "react-native";
import colors from "../../config/colors";

const styles = StyleSheet.create({ 
    container:{
        height:'100%'
    },
  head:{
      height:'35%',
      backgroundColor:colors.green,
      borderBottomLeftRadius:100,
      borderBottomRightRadius:100,
      alignItems:'center'
      
  },
  box:{
      height:'80%',
      width:'80%',
      backgroundColor:colors.white,
      marginTop:'30%',
      elevation:15,
      shadowColor:colors.green,
      shadowOpacity:0.50,
      borderRadius:15,
      alignItems:'center'
      
  },
  img:{
      height:'50%',
      width:'35%',
      borderRadius:200,
      marginTop:'5%'
  },
  name:{
      marginTop:10,
      fontFamily:'Poppins_500Medium',
      fontSize:20,      
  },
  class:{
      fontFamily:'Poppins_300Light',
      fontSize:15,
      color:colors.blue,
  },
  contactbox:{
      alignItems:'center',
      width:'100%',
      height:'12%'
  },
  contact:{
      marginTop:'30%',
      width:'80%',
      height:'100%',
      backgroundColor:colors.white,
      elevation:15,
      shadowColor:colors.green,
      shadowOpacity:0.50,
      borderRadius:10,
      justifyContent:'center',    
  },
  txt:{
      marginLeft:30,
      fontSize:15,
    fontFamily:'Poppins_500Medium',   
  },
  attendancebox:{
      height:220,
      width:'80%',
      marginTop:'10%',
      backgroundColor:colors.white,
      elevation:15,
      shadowColor:colors.green,
      shadowOpacity:0.50,
      borderRadius:10,
  },
  header:{
      height:'30%',
      marginTop:'-6%',
      borderTopLeftRadius:10,
      borderTopRightRadius:10,
      borderBottomWidth:1,
      borderBottomColor:'black',
    
  },
  headertxt:{
      fontSize:10,
      fontFamily:'Poppins_500Medium',
      fontSize:20,
      marginTop:'10%',
      marginLeft:'5%',
      opacity:0.6,
  },
  infobox:{
    
      width:'100%',
      flexDirection:'row',
      justifyContent:'space-around',
      marginTop:'10%',
  },
  databox:{
      alignItems:'center',
      backgroundColor:colors.white,
      height:80,
      width: 80,
      borderRadius:10,
      elevation:2,
      shadowColor:colors.black,
      shadowOpacity:0.10,
      justifyContent:'center'
  },
  infotxt:{
    fontFamily:'Poppins_500Medium',
    opacity:0.5,
    fontSize:15
  },
  datatxt:{
    fontFamily:'Poppins_500Medium',
    opacity:0.5,
    fontSize:20
  }
});

export default styles;
